name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12h, no início da hora
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: luannllopes
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
